# to build site quickly, run:
#
#  npx antora antora-playbook.yml
#
# to activate the diagram generator (Kroki), run:
#
#  npx --package antora --package asciidoctor-kroki antora antora-playbook.yml
#
# to run the full production build, start by installing all the required dependencies:
#
#  npm i --package-lock false
#
# then run:
#
#  ANTORA_CACHE_DIR=$PWD/.cache/antora npx --offline antora --extension @antora/collector-extension --extension @antora/lunr-extension --extension jetty-downloads-extension antora-playbook.yml
antora:
  extensions:
  - ./lib/register-asciidoctor-kroki-extension.js
  - ./lib/component-url-prefix-extension.js
  - id: jetty-downloads-extension
    require: ./lib/jetty-downloads-extension.js
    enabled: false
    last_eol_version: 11
site:
  title: Eclipse Jetty
  url: https://jetty.org
  keys:
    google_analytics: G-VS4ZRD6HVM
content:
  sources:
  - url: .
    branches: HEAD
    start_paths: [home, docs-home, contribution-guide]
  - url: https://github.com/opendevise/jetty.project
    branches: jetty-{12,11,10}.0.x-for-antora
    start_path: documentation/jetty
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
  - ./lib/feed-block-macro.js
  - ./lib/jetty-block.js
  - ./lib/skip-include-processor.js
  - ./lib/absolute-path-include-processor.js
ui:
  bundle:
    url: https://github.com/webtide/jetty.website/releases/download/ui-prod-latest/ui-bundle.zip
    snapshot: true
output:
  dir: ./_site
