# to build site quickly, run:
#
#  mvn antora
#
# which is equivalent to:
#
#  npx antora --clean --fetch antora-playbook.yml
#
# to activate the diagram generator (Kroki), run:
#
#  mvn antora:antora@kroki
#
# which is equivalent to:
#
#  npx --package antora --package asciidoctor-kroki antora --extension register-asciidoctor-kroki antora-playbook.yml
#
# to run the full production build, run:
#
#  mvn antora:antora@full
#
# which is equivalent to:
#
#  npm i --package-lock false
#  ANTORA_CACHE_DIR=$PWD/.cache/antora npx --offline antora --clean --fetch --extension @antora/collector-extension --extension @antora/lunr-extension --extension jetty-downloads --extension register-asciidoctor-kroki --log-failure-level warn --stacktrace antora-playbook.yml
antora:
  extensions:
  - ./lib/component-url-prefix-extension.js
  - id: jetty-downloads
    require: ./lib/jetty-downloads-extension.js
    enabled: false
    last_eol_version: 11
  - id: register-asciidoctor-kroki
    require: ./lib/register-asciidoctor-kroki-extension.js
    enabled: false
site:
  title: Eclipse Jetty
  url: https://jetty.org
  keys:
    google_analytics: G-VS4ZRD6HVM
content:
  sources:
  - url: .
    branches: HEAD
    start_paths: [home, docs-home, contribution-guide]
  - url: https://github.com/opendevise/jetty.project
    branches: jetty-{12,11,10}.0.x-for-antora
    start_path: documentation/jetty
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
  - ./lib/feed-block-macro.js
  - ./lib/jetty-block.js
  - ./lib/skip-include-processor.js
  - antora-asciidoctor-extensions/absolute-path-include-processor
ui:
  bundle:
    url: https://github.com/webtide/jetty.website/releases/download/ui-prod-latest/ui-bundle.zip
    snapshot: true
output:
  dir: target/site
